### ISSUE TITLE
Add support for codeclimate

### ISSUE THREAD

**Issue by Mattamorphic** [Matt-Barber/DataCruncher#31]
commit a YML with the following: 

```
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
```
